### ISSUE TITLE
Adding Own source?

### ISSUE THREAD

**Issue by LiamKenyon** [sfanous/IPTVProxy#1]
Looking through and is it possible to only have available 1 source?

Also, can I had a source that doesn’t currently have setup?

**Comment by sfanous** [comment]
You can have any number of sources/providers configured, so 1 source/provider should be just fine.

I'm not getting your second question.

**Comment by LiamKenyon** [comment]
Apologies bad wording.

I want to use a source that you don’t currently have listed. But would like to enter only have to enter user & pass is there a way I can set this up.

**Comment by sfanous** [comment]
If the source/provider is not already supported then support for it has to be added first.

Just adding the user/password details won't make it work.

As I keep trialing different providers and as time permits I add additional sources/providers. The easiest ones to add are the ones that are based on IPTV Smarters.

**Comment by LiamKenyon** [comment]
getting the following error when installing:

```
Traceback (most recent call last):
  File "iptv_proxy_runner.py", line 4, in <module>
    from iptv_proxy.main import main
  File "/root/IPTVProxy/iptv_proxy/main.py", line 1, in <module>
    import logging
  File "/root/IPTVProxy/iptv_proxy/logging.py", line 5, in <module>
    import logging.config
ImportError: No module named config

```

Any ideas?

**Comment by sfanous** [comment]
This error indicates that you're using a Python 2 interpreter. IPTVProxy only works with Python 3.6+.
